### ISSUE TITLE
Wrong diff result for totally-inside polygon

### ISSUE THREAD

**Issue by romka-chev** [platener/GreinerHormann#11]
Hello! 

Here is example:

``` JS
greinerHormann.diff([[0,0], [0,3], [3,3], [3,0]], [[1,1], [1,2], [2,2], [2,1]])
```

And it returns just the second polygon:

``` JS
[[1,1], [1,2], [2,2], [2,1]]
```

But i've expect something like this:

``` JS
[
    [[0,0], [0,3], [3,3], [3,0]], // shape
    [[1,1], [1,2], [2,2], [2,1]], // hole 1
//  [[X,Y], [X,Y], [X,Y], [X,Y]], // hole N
]
```

Is this behavior is by design?

P.S. Sorry for my engrish.

**Comment by romka-chev** [comment]
And another question:

Is this repo abandoned and I should use this one https://github.com/platener/jsclipper ?

**Comment by mischkew** [comment]
Hey there,

degenaries cannot be solved for 100 percent with the Greiner Hormann algorithm. 
The problem you encounter could surely be tackled, but we currently do not work on this project anymore. Maybe have a look at this: 

https://github.com/w8r/GreinerHormann

JSClipper a port from this library

http://www.angusj.com/delphi/clipper.php

We just wrote an adapter on top of this javascript library:

http://sourceforge.net/projects/jsclipper/

We work with jsclipper now and it is more likely that we will fix bugs :)
I hope this helps. Let me know more otherwise

**Comment by mischkew** [comment]
Or even this one (implements degeneracies) 
https://github.com/tcql/greiner-hormann

**Comment by romka-chev** [comment]
Thank you for quick reply!

Please tell me, can this problem be solved by JSClipper port?

**Comment by mischkew** [comment]
So this is jsclipper related. Lets discuss this here: https://github.com/platener/jsclipper/issues/5
